server:
  port: 8762 
  
spring: 
  application: 
    name: hystrix-movie
eureka:  
  client: 
    healthcheck: 
      enabled: true
    service-url: 
      defaultZone: http://user:123@localhost:8760/eureka
  instance: 
    prefer-ip-address: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000


      
